version: 2
jobs:
  build:
    working_directory: /tmp/hello-world
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-cache
      - run: npm i
      - save_cache:
          key: node-modules-cache
          paths:
            - node_modules/
      - persist_to_workspace:
          root: /tmp/hello-world
          paths:
            - .
  test:
    docker:
      - image: circleci/node:11.15.0-stretch-browsers
    steps:
      - attach_workspace:
          at: .
      - run: 
          command: |
            node server.js
          background: true
      # Wait for server to come online
      - run: sleep 2
      - run: npm run test-chrome
      - run: npm run test-firefox
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy app to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
 
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master