version: 2
jobs:
  build:
    working_directory: /tmp/hello-world
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm i
      - persist_to_workspace:
          root: /tmp/hello-world
          paths:
            - .
  test:
    docker:
      - image: circleci/node:11.15.0-stretch-browsers
    steps:
      - attach_workspace:
          at: .
      - run: ls -alh
      - run: 
          command: |
            node server.js
          background: true
      - run: |
          sleep 5
          curl http://localhost:8080
      - run: npm run test-chrome
      - run: npm run test-firefox
 
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master