version: 2

commands:
  npm_test:
    description: "NPM run command with basic server"
    parameters:
      test:
        type: string
        default: ""
      server:
        type: string
        default: "server.js"
    steps:
      - run: 
          command: |
            node <<parameters.server>>
          background: true
      # Wait for server to come online
      - run: sleep 2
      - run: npm run <<parameters.test>>

jobs:
  build:
    working_directory: /tmp/hello-world
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-cache
      - run: npm i
      - save_cache:
          key: node-modules-cache
          paths:
            - node_modules/
      - persist_to_workspace:
          root: /tmp/hello-world
          paths:
            - .

  test_chrome:
    docker:
      - image: circleci/node:11.15.0-stretch-browsers
    steps:
      - attach_workspace:
          at: .
      - npm_test:
          test: test-chrome

  test_firefox:
    docker:
      - image: circleci/node:11.15.0-stretch-browsers
    steps:
      - attach_workspace:
          at: .
      - npm_test:
          test: test-firefox

  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy app to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
 
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test_chrome:
          requires:
            - build
          filters:
            branches:
              only: master
      - test_firefox:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - test_chrome
            - test_firefox
          filters:
            branches:
              only: master