version: 2
jobs:
  build:
    working_directory: /hello-world
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
      - store_artifacts:
          path:  /hello-world
      - persist_to_workspace:
          root: /hello-world
          paths:
            - .
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - attach_workspace:
          at: .
      - run: nohup npm start &
      - run: npm test-chrome
      - run: npm test-firefox
 
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master